import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ee7ebb",
        "surface-container-highest": "#1A1A1A",
        "on-primary-fixed-variant": "#1d0098",
        "on-primary-container": "#16007d",
        "on-tertiary": "#6c0f4c",
        "surface-container-lowest": "#000000",
        "tertiary": "#ff9dd0",
        "on-background": "#E2E2E2",
        "error-dim": "#d73357",
        "outline-variant": "#464555",
        "on-secondary": "#005c57",
        "on-surface": "#E2E2E2",
        "inverse-primary": "#5044e3",
        "secondary": "#7cf6ec",
        "inverse-on-surface": "#525369",
        "tertiary-dim": "#eb7bb8",
        "on-surface-variant": "#464555",
        "error": "#ff6e84",
        "surface-container": "#0E0E0E",
        "primary": "#E2E2E2",
        "surface-dim": "#000000",
        "surface": "#000000",
        "secondary-container": "#006a65",
        "primary-fixed": "#9995ff",
        "primary-dim": "#675df9",
        "background": "#000000",
        "on-tertiary-container": "#5e0041",
        "inverse-surface": "#fbf8ff",
        "tertiary-fixed": "#fe8bc9",
        "surface-container-high": "#111111",
        "outline": "#464555",
        "on-secondary-fixed-variant": "#006761",
        "on-secondary-container": "#dbfffa",
        "secondary-fixed": "#7cf6ec",
        "surface-variant": "#0E0E0E",
        "error-container": "#a70138",
        "on-tertiary-fixed": "#360023",
        "on-primary": "#000000",
        "tertiary-container": "#fb88c6",
        "primary-fixed-dim": "#8a85ff",
        "on-error": "#490013",
        "surface-container-low": "#080808",
        "on-error-container": "#ffb2b9",
        "surface-tint": "#E2E2E2",
        "secondary-dim": "#6ce8de",
        "on-primary-fixed": "#000000",
        "on-secondary-fixed": "#004844",
        "secondary-fixed-dim": "#6ce8de",
        "primary-container": "#1A1A1A",
        "surface-bright": "#1A1A1A",
        "on-tertiary-fixed-variant": "#6d104c"
      },
      fontFamily: {
        "headline": ["var(--font-plus-jakarta)"],
        "body": ["var(--font-manrope)"],
        "label": ["var(--font-manrope)"]
      },
    },
  },
  plugins: [],
};
export default config;